default:
	@just --list

generate:
	protoc \
		-I=. \
		--go_out=pb \
		--go_opt="paths=source_relative" \
		--go-grpc_out=pb \
		--go-grpc_opt="paths=source_relative" \
		./*.proto

serve:
	GRPC_GO_LOG_SEVERITY_LEVEL=info GRPC_GO_LOG_VERBOSITY_LEVEL=99 go run ./server

unary:
	GRPC_GO_LOG_SEVERITY_LEVEL=info GRPC_GO_LOG_VERBOSITY_LEVEL=99 go run ./client/unary
stream:
	GRPC_GO_LOG_SEVERITY_LEVEL=info GRPC_GO_LOG_VERBOSITY_LEVEL=99 go run ./client/stream
pingpong:
	GRPC_GO_LOG_SEVERITY_LEVEL=info GRPC_GO_LOG_VERBOSITY_LEVEL=99 go run ./client/pingpong
